[package]
name = "main"
version = "0.1.0"
authors = ["Masahiro Yoshida <mypianoplayer@gmail.com>"]
edition = "2018"

[dependencies]
libc = "*"
libloading = "*"
simple-error = "*"
tokio = "0.1.20"
futures = "0.1.25"
bytes = "0.4.11"
lazy_static = "1.2.0"
